import React from 'react'
import {
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUpRight,
  BracketsCurly,
  Briefcase,
  ChatCircleText,
  ChatsCircle,
  CheckCircle,
  Code,
  Envelope,
  FigmaLogo,
  FolderOpen,
  GearSix,
  GithubLogo,
  InstagramLogo,
  LinkedinLogo,
  List,
  MapPin,
  Moon,
  PaperPlaneTilt,
  PenNib,
  Quotes,
  SignOut,
  Sparkle,
  Sun,
  ThreadsLogo,
  WhatsappLogo,
  X,
  XLogo,
  YoutubeLogo
} from '@phosphor-icons/react'

// Custom SVGs
import CursorIcon from './CursorIcon'
import GoogleAIStudioIcon from './GoogleAIStudioIcon'
import HermesAgentsIcon from './HermesAgentsIcon'
import PiAgentIcon from './PiAgentIcon'

export {
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUpRight,
  BracketsCurly,
  Briefcase,
  ChatCircleText,
  ChatsCircle,
  CheckCircle,
  Code,
  Envelope,
  FigmaLogo,
  FolderOpen,
  GearSix,
  GithubLogo,
  InstagramLogo,
  LinkedinLogo,
  List,
  MapPin,
  Moon,
  PaperPlaneTilt,
  PenNib,
  Quotes,
  SignOut,
  Sparkle,
  Sun,
  ThreadsLogo,
  WhatsappLogo,
  X,
  XLogo,
  YoutubeLogo,
  CursorIcon,
  GoogleAIStudioIcon,
  HermesAgentsIcon,
  PiAgentIcon
}
